model ObsAvoidController_Sysblock7g1 "避障控制+差速（Sysblock）决赛版本"
  extends ModelWorkspace;
  import SysplorerEmbeddedCoder.Types.*;
  import BaseWorkspace.*;
  annotation(__MWORKS(version="26.3.0",modelType=Control,PortArrangement(Left(front_dist, fl_dist, right_dist, left_dist, fr_dist), Right(speed, steer, gap)),BlockSystem(blockKind=BlockKind.userModel,SampleTime(auto=true,group="")=0.05),SysblockVersion="1.0",ContinueSimConfig(SaveContinueFile="false",SaveBeforeStop="false",NumberBeforeStop=1,FixedContinueInterval="false",ContinueIntervalLength=100,ContinueTimeVector)),Icon(coordinateSystem(preserveAspectRatio=false)),experiment(Algorithm=Rkfix4,Interval=0.05,InlineIntegrator=false,InlineStepSize=false,StartTime=0,StopTime=100,Tolerance=0.0001,IntegratorStep=0.05),Diagram(coordinateSystem(extent={{-100,-100},{100,100}},
grid={2,2}),graphics = {Text(origin={-171,58},
lineColor={0,0,0},
extent={{-19,10},{19,-10}},
textString="前方传感器距离",
textStyle={TextStyle.None},
textColor={0,0,0},
horizontalAlignment=LinePattern.None), Text(origin={-171,16},
lineColor={0,0,0},
extent={{-19,10},{19,-10}},
textString="左前方传感器距离",
textStyle={TextStyle.None},
textColor={0,0,0},
horizontalAlignment=LinePattern.None), Text(origin={-171,-64.3},
lineColor={0,0,0},
extent={{-19,10},{19,-10}},
textString="左方传感器距离",
textStyle={TextStyle.None},
textColor={0,0,0},
horizontalAlignment=LinePattern.None), Text(origin={-171,-18.6},
lineColor={0,0,0},
extent={{-19,10},{19,-10}},
textString="右方传感器距离",
textStyle={TextStyle.None},
textColor={0,0,0},
horizontalAlignment=LinePattern.None), Text(origin={221,58},
lineColor={0,0,0},
extent={{-19,10},{19,-10}},
textString="预期车速",
textStyle={TextStyle.None},
textColor={0,0,0},
horizontalAlignment=LinePattern.None), Text(origin={221,-58},
lineColor={0,0,0},
extent={{-19,10},{19,-10}},
textString="前轮转角",
textStyle={TextStyle.None},
textColor={0,0,0},
horizontalAlignment=LinePattern.None), Text(origin={-171,-110},
lineColor={0,0,0},
extent={{-19,10},{19,-10}},
textString="右前方传感器距离",
textStyle={TextStyle.None},
textColor={0,0,0},
horizontalAlignment=LinePattern.None), Text(origin={221,-110},
lineColor={0,0,0},
extent={{-19,10},{19,-10}},
textString="后轮差速",
textStyle={TextStyle.None},
textColor={0,0,0},
horizontalAlignment=LinePattern.None)}));
  SysplorerEmbeddedCoder.Port.Inport front_dist 
    annotation (Placement(transformation(origin={-136,58},
extent={{-10,-10},{10,10}}),
iconTransformation(origin={-101.8,80},
extent={{-1.8,-1.8},{1.8,1.8}})),__MWORKS(BlockSystem(Type(inherit=InheritType.none ,ref="double") ,Dimension(dimensionType=DimensionType.none)=1 ,SampleTime(group="D1")=0.02)));
  SysplorerEmbeddedCoder.Port.Inport fl_dist 
    annotation (Placement(transformation(origin={-136,16},
extent={{-10,-10},{10,10}}),
iconTransformation(origin={-101.8,40},
extent={{-1.8,-1.8},{1.8,1.8}})),__MWORKS(BlockSystem(Type(inherit=InheritType.none ,ref="double") ,Dimension(dimensionType=DimensionType.none)=1 ,SampleTime(group="D1")=0.02)));
  SysplorerEmbeddedCoder.Port.Inport left_dist 
    annotation (Placement(transformation(origin={-136,-64.3},
extent={{-10,-10},{10,10}}),
iconTransformation(origin={-101.8,-40},
extent={{-1.8,-1.8},{1.8,1.8}})),__MWORKS(BlockSystem(Type(inherit=InheritType.none ,ref="double") ,Dimension(dimensionType=DimensionType.none)=1 ,SampleTime(group="D1")=0.02)));
  SysplorerEmbeddedCoder.Port.Inport right_dist 
    annotation (Placement(transformation(origin={-136,-18.6},
extent={{-10,-10},{10,10}}),
iconTransformation(origin={-101.8,0},
extent={{-1.8,-1.8},{1.8,1.8}})),__MWORKS(BlockSystem(Type(inherit=InheritType.none ,ref="double") ,Dimension(dimensionType=DimensionType.none)=1 ,SampleTime(group="D1")=0.02)));
  SysplorerEmbeddedCoder.Port.Outport speed 
    annotation (Placement(transformation(origin={178,58},
extent={{-10,-10},{10,10}}),
iconTransformation(origin={101.8,66.6667},
extent={{-1.8,-1.8},{1.8,1.8}})),__MWORKS(BlockSystem(Type(inherit=InheritType.none ,ref="double") ,Dimension(dimensionType=DimensionType.none)=1 ,SampleTime(group="D1")=0.02)));
  SysplorerEmbeddedCoder.Port.Outport steer 
    annotation (Placement(transformation(origin={178,-58},
extent={{-10,-10},{10,10}}),
iconTransformation(origin={101.8,0},
extent={{-1.8,-1.8},{1.8,1.8}})),__MWORKS(BlockSystem(Type(inherit=InheritType.none ,ref="double") ,Dimension(dimensionType=DimensionType.none)=1 ,SampleTime(group="D1")=0.02)));
  Chart chart 
    annotation (Placement(transformation(origin={-18,-7},
extent={{-29,-29},{29,29}})),__MWORKS(ComponentNamePlacement(BOTTOM),BlockSystem(SampleTime(group="D1")=0.02)));
  SysplorerEmbeddedCoder.MathOperation.Sum sum1(isSaturate=false,inputs="+-") 
    annotation (Placement(transformation(origin={140,28},
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(Instance(u(u1(Type(ref="double") ,Dimension=1) ,u2(Type(ref="double") ,Dimension=1)) ,y(Type(ref="double") ,Dimension=1)),Type(overflowKind=SysplorerEmbeddedCoder.Types.OverflowKind.wrap) ,SampleTime(group="D1")=0.02),PortLabels(labelType="CustomType",labels(label(text="+",instance="u1"),label(text="-",instance="u2")))));
  SysplorerEmbeddedCoder.MathOperation.Sum sum2(isSaturate=false,inputs="++") 
    annotation (Placement(transformation(origin={52,-26.5},
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(Instance(u(u1(Type(ref="double") ,Dimension=1) ,u2(Type(ref="double") ,Dimension=1)) ,y(Type(ref="double") ,Dimension=1)),Type(overflowKind=SysplorerEmbeddedCoder.Types.OverflowKind.wrap) ,SampleTime(group="D1")=0.02),PortLabels(labelType="CustomType",labels(label(text="+",instance="u1"),label(text="+",instance="u2")))));
  SysplorerEmbeddedCoder.Sources.Constant constant1(k=pi) 
    annotation (Placement(transformation(origin={1,-58},
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(SampleTime(auto=true,group="D1")=0.02,Instance(y(Type(ref="double") ,Dimension=1) ,k(Type(ref="double") ,Dimension=1)))));
  SysplorerEmbeddedCoder.MathOperation.RoundingFunction roundingFunction 
    annotation (Placement(transformation(origin={62,16},
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(Instance(u(Type(ref="double") ,Dimension=1) ,y(Type(ref="double") ,Dimension=1)),SampleTime(group="D1")=0.02)));
  SysplorerEmbeddedCoder.MathOperation.Product product1(isSaturate=false,inputs="*/") 
    annotation (Placement(transformation(origin={94,-31.5},
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(Instance(u(u1(Type(ref="double") ,Dimension=1) ,u2(Type(ref="double") ,Dimension=1)) ,y(Type(ref="double") ,Dimension=1)),Type(overflowKind=SysplorerEmbeddedCoder.Types.OverflowKind.wrap) ,SampleTime(group="D1")=0.02),PortLabels(labelType="CustomType",labels(label(text="*",instance="u1"),label(text="/",instance="u2")))));
  SysplorerEmbeddedCoder.Sources.Constant constant2(k=2*pi) 
    annotation (Placement(transformation(origin={52,-58},
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(SampleTime(auto=true,group="D1")=0.02,Instance(y(Type(ref="double") ,Dimension=1) ,k(Type(ref="double") ,Dimension=1)))));
  SysplorerEmbeddedCoder.MathOperation.Gain gain(k=2*pi) 
    annotation (Placement(transformation(origin={94,16},
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(Instance(u(Type(ref="double") ,Dimension=1) ,y(Type(ref="double") ,Dimension=1) ,k(Type(ref="double") ,Dimension=1)),SampleTime(group="D1")=0.02)));
  SysplorerEmbeddedCoder.MathOperation.Abs abs1 
    annotation (Placement(transformation(origin={-98,58},
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(Instance(u(Type(ref="double") ,Dimension=1) ,y(Type(ref="double") ,Dimension=1)),SampleTime(group="D1")=0.02)));
  SysplorerEmbeddedCoder.MathOperation.Abs abs2 
    annotation (Placement(transformation(origin={-98,16},
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(Instance(u(Type(ref="double") ,Dimension=1) ,y(Type(ref="double") ,Dimension=1)),SampleTime(group="D1")=0.02)));
  SysplorerEmbeddedCoder.MathOperation.Abs abs3 
    annotation (Placement(transformation(origin={-98,-64.3},
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(Instance(u(Type(ref="double") ,Dimension=1) ,y(Type(ref="double") ,Dimension=1)),SampleTime(group="D1")=0.02)));
  SysplorerEmbeddedCoder.MathOperation.Abs abs4 
    annotation (Placement(transformation(origin={-98,-18.6},
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(Instance(u(Type(ref="double") ,Dimension=1) ,y(Type(ref="double") ,Dimension=1)),SampleTime(group="D1")=0.02)));
  SysplorerEmbeddedCoder.Discontinuities.Saturation saturation(zeroCross=true,upLimit=0.8,lowLimit=-0.8) 
    annotation (Placement(transformation(origin={140,-31.5},
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(zeroCross=true ,Instance(dynamicSaturation(upperLimit(Type(ref="double") ,Dimension=1) ,u(Type(ref="double") ,Dimension=1) ,lowerLimit(Type(ref="double") ,Dimension=1) ,y(Type(ref="double") ,Dimension=1)) ,u(Type(ref="double") ,Dimension=1) ,y(Type(ref="double") ,Dimension=1) ,constant_up(y(Type(ref="double") ,Dimension=1) ,k(Type(ref="") ,Dimension=1)) ,constant_low(y(Type(ref="double") ,Dimension=1) ,k(Type(ref="") ,Dimension=1)) ,upLimit(Type(ref="") ,Dimension=1) ,lowLimit(Type(ref="") ,Dimension=1)),SampleTime(group="D1")=0.02)));
  SysplorerEmbeddedCoder.Port.Inport fr_dist 
    annotation (Placement(transformation(origin={-136,-110},
extent={{-10,-10},{10,10}}),
iconTransformation(origin={-101.8,-80},
extent={{-1.8,-1.8},{1.8,1.8}})),__MWORKS(BlockSystem(Type(inherit=InheritType.none ,ref="double") ,Dimension(dimensionType=DimensionType.none)=1 ,SampleTime(group="D1")=0.02)));
  SysplorerEmbeddedCoder.MathOperation.Abs abs5 
    annotation (Placement(transformation(origin={-98,-110},
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(Instance(u(Type(ref="double") ,Dimension=1) ,y(Type(ref="double") ,Dimension=1)),SampleTime(group="D1")=0.02)));
  SysplorerEmbeddedCoder.Port.Outport gap 
    annotation (Placement(transformation(origin={178,-110},
extent={{-10,-10},{10,10}}),
iconTransformation(origin={101.8,-66.6667},
extent={{-1.8,-1.8},{1.8,1.8}})),__MWORKS(BlockSystem(Type(ref="double"),Dimension=1,SampleTime(group="D1")=0.02)));
  SysplorerEmbeddedCoder.MathOperation.Gain gain1(k=1) 
    annotation (Placement(transformation(origin={102,58},
extent={{-10,-10},{10,10}})),__MWORKS(BlockSystem(Instance(u(Type(ref="double") ,Dimension=1) ,y(Type(ref="double") ,Dimension=1) ,k(Type(ref="double") ,Dimension=1)),SampleTime(group="D1")=0.02)));
  block Chart "状态机"
    annotation (__MWORKS(BlockSystem(blockKind = BlockKind.stateMachine,SampleTime(auto = true),independent = true,StateMachine(virtual = false,functionPack = FunctionPack.auto,functionName = "",sourceFile = "",parallel=true)),PortArrangement(Left(df, dfl, dr, dl, dfr), Right(speed, steer, gapS)),sourceModel=SysplorerEmbeddedCoder.StateMachine.Chart,independentInstance=true,hide=true),
      defaultComponentName = "chart",
      Icon(coordinateSystem(extent = {{-100.0, -100.0}, {100.0, 100.0}},
        grid = {2.0, 2.0}), graphics = {Rectangle(origin = {0.0, 0.0},
        lineColor = {74, 84, 154},
        fillColor = {255, 255, 255},
        lineThickness = 1.0,
        extent = {{-100.0, 100.0}, {100.0, -100.0}},
        radius = 11.0), Rectangle(origin = {0.0, 27.0},
        lineColor = {74, 84, 154},
        fillColor = {255, 255, 255},
        lineThickness = 1.0,
        extent = {{-25.0, 20.0}, {25.0, -20.0}},
        radius = 10.0), Rectangle(origin = {-40.0, -27.0},
        lineColor = {74, 84, 154},
        fillColor = {255, 255, 255},
        lineThickness = 1.0,
        extent = {{-25.0, 20.0}, {25.0, -20.0}},
        radius = 10.0), Rectangle(origin = {40.0, -27.0},
        lineColor = {74, 84, 154},
        fillColor = {255, 255, 255},
        lineThickness = 1.0,
        extent = {{-25.0, 20.0}, {25.0, -20.0}},
        radius = 10.0), Line(origin = {-40.0, 13.0},
        points = {{-10.0, -13.0}, {-10.0, 7.0}, {10.0, 13.0}},
        color = {74, 84, 154},
        thickness = 1.0,
        arrow = {Arrow.None, Arrow.Filled},
        arrowSize = 8.0,
        smooth = Smooth.Bezier), Line(origin = {41.0, 13.0},
        points = {{-9.0, 13.0}, {9.0, 11.0}, {9.0, -13.0}},
        color = {74, 84, 154},
        thickness = 1.0,
        arrow = {Arrow.None, Arrow.Filled},
        arrowSize = 8.0,
        smooth = Smooth.Bezier), Line(origin = {0.0, -28.0},
        points = {{10.0, 0.0}, {-10.0, 0.0}},
        color = {74, 84, 154},
        thickness = 1.0,
        arrow = {Arrow.None, Arrow.Filled},
        arrowSize = 8.0,
        smooth = Smooth.Bezier), Text(origin = {0.0, -120.0},
        lineColor = {74, 84, 154},
        extent = {{0, 20.0}, {0, -20.0}},
        textString = "%name",
        fontSize = 14,
        textStyle = {TextStyle.None},
        textColor = {74, 84, 154},
        verticalAlignment = TextAlignment.Top)}),Protection(access=Access.packageDuplicate),Diagram(coordinateSystem(extent={{-100,-100},{100,100}},
  grid={2,2})));
    SysplorerEmbeddedCoder.Port.Inport df annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)),Placement(iconTransformation(extent={{-1.8, -1.8}, {1.8, 1.8}})));
    SysplorerEmbeddedCoder.Port.Inport dfl annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)),Placement(iconTransformation(extent={{-1.8, -1.8}, {1.8, 1.8}})));
    SysplorerEmbeddedCoder.Port.Inport dr annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)),Placement(iconTransformation(extent={{-1.8, -1.8}, {1.8, 1.8}})));
    SysplorerEmbeddedCoder.Port.Inport dl annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)),Placement(iconTransformation(extent={{-1.8, -1.8}, {1.8, 1.8}})));
    SysplorerEmbeddedCoder.Port.Outport speed(start=0) annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)),Placement(iconTransformation(extent={{-1.8, -1.8}, {1.8, 1.8}})));
    SysplorerEmbeddedCoder.Port.Outport steer(start=0) annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)),Placement(iconTransformation(extent={{-1.8, -1.8}, {1.8, 1.8}})));
    SysplorerEmbeddedCoder.Types.Auto mindis(start=10) annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)));
    SysplorerEmbeddedCoder.Types.Auto safeF(start=40) annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)));
    State longitudinal 
      annotation (Placement(transformation(origin={-279,-27.5},
  extent={{-129,-90.5},{129,90.5}})),__MWORKS(BlockSystem(StateMachine(priority=1))));
    SysplorerEmbeddedCoder.Types.Auto flag(start=false) annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="boolean"),Dimension(dimensionType=DimensionType.none)=1)));
    SysplorerEmbeddedCoder.Types.Auto speedC(start=10) annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)));
    SysplorerEmbeddedCoder.Types.Auto speedA(start=-5) annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)));
    SysplorerEmbeddedCoder.Types.Auto steerA(start=0.523) annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)));
    SysplorerEmbeddedCoder.Port.Inport dfr annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)),Placement(iconTransformation(extent={{-1.8, -1.8}, {1.8, 1.8}})));
    State1 lateral 
      annotation (Placement(transformation(origin={-29,-264},
extent={{-379,-138},{379,138}})),__MWORKS(BlockSystem(StateMachine(priority=2))));
    SysplorerEmbeddedCoder.Types.Auto safeFLR(start=20) annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)));
    State2 gap if false 
      annotation (Placement(transformation(origin={104.5,-27.5},
extent={{-245.5,-90.5},{245.5,90.5}})),__MWORKS(BlockSystem(StateMachine(priority=3))));
    SysplorerEmbeddedCoder.Port.Outport gapS(start=0) annotation (__MWORKS(internalShare = true,BlockSystem(Type(inherit=InheritType.none,ref="double"),Dimension(dimensionType=DimensionType.none)=1)),Placement(iconTransformation(extent={{-1.8, -1.8}, {1.8, 1.8}})));
    block State "状态"
      annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state",
       Icon(coordinateSystem(extent={{-100, -100}, {100, 100}},
         grid={2, 2}), graphics={Rectangle(origin = {0, 0},
         lineColor = {74, 84, 154},
         fillColor = {255, 255, 255},
         lineThickness = 1,
         extent = {{-100, 100}, {100, -100}},
         radius = 11), Line(origin = {0, 80},
         points = {{-100, 0}, {100, 0}},
         color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90},
         lineColor = {0, 0, 128},
         extent = {{-100, 10}, {100, -10}},
         textString = "%name",
         textStyle = {TextStyle.None},
         textColor = {0, 0, 128}), Text(origin = {0, -10},
         lineColor = {0, 0, 128},
         extent = {{-100, 90}, {100, -90}},
         textString = "algorithm",
         fontSize = 16,
         textStyle = {TextStyle.None},
         textColor = {0, 0, 128},
         horizontalAlignment = TextAlignment.Left,
         verticalAlignment = TextAlignment.Top)}),
       Diagram(coordinateSystem(extent={{-129,-90.5},{129,90.5}},
  initialScale=1,
  grid={2,2}),graphics = {State(origin={0,0},
  stateTitle=Text(origin={0,0},
  lineColor={74,84,154},
  extent={{-127,82.5},{127,90.5}},
  textString="%name",
  fontSize=16,
  textStyle={TextStyle.Bold},
  textColor={74,84,154},
  horizontalAlignment=TextAlignment.Left),
  stateText=Text(origin={0,0},
  lineColor={74,84,154},
  extent={{-127,-90.5},{127,82.5}},
  textString="%algorithm",
  fontSize=16,
  textColor={74,84,154},
  horizontalAlignment=TextAlignment.Left,
  verticalAlignment=TextAlignment.Top))}),Protection(access=Access.packageDuplicate));
      block State2 "状态"
        annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state",
         Icon(coordinateSystem(extent={{-100, -100}, {100, 100}},
           grid={2, 2}), graphics={Rectangle(origin = {0, 0},
           lineColor = {74, 84, 154},
           fillColor = {255, 255, 255},
           lineThickness = 1,
           extent = {{-100, 100}, {100, -100}},
           radius = 11), Line(origin = {0, 80},
           points = {{-100, 0}, {100, 0}},
           color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90},
           lineColor = {0, 0, 128},
           extent = {{-100, 10}, {100, -10}},
           textString = "%name",
           textStyle = {TextStyle.None},
           textColor = {0, 0, 128}), Text(origin = {0, -10},
           lineColor = {0, 0, 128},
           extent = {{-100, 90}, {100, -90}},
           textString = "algorithm",
           fontSize = 16,
           textStyle = {TextStyle.None},
           textColor = {0, 0, 128},
           horizontalAlignment = TextAlignment.Left,
           verticalAlignment = TextAlignment.Top)}),
         Diagram(coordinateSystem(extent={{-40, -30}, {40, 30}}, initialScale=1, grid={2, 2}), graphics = {State(origin = {0.0, 0.0},
              stateTitle = Text(origin = {0, 0},
              lineColor = {74, 84, 154},
              extent = {{-38, 22}, {38, 30}},
              textString = "%name",
              fontSize = 16,
              horizontalAlignment = TextAlignment.Left,
              textStyle = {TextStyle.Bold},
              textColor = {74, 84, 154},
              verticalAlignment = TextAlignment.Center),
              stateLine = Line(origin={0,0},
              color = {74, 84, 154},
              points={{-40,22},{40,22}}),
              stateText = Text(origin = {0.0, 0.0},
              lineColor = {74, 84, 154},
              extent = {{-38, -30}, {38, 22}},
              textString = "%algorithm",
              fontSize = 16,
              textColor = {74, 84, 154},
              horizontalAlignment = TextAlignment.Left,
              verticalAlignment = TextAlignment.Top))}),Protection(access=Access.packageDuplicate));
      algorithm
      annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));  speed := -20;
        flag := false;
      end State2;
      State2 cruise 
      annotation(Placement(transformation(origin={-79,16.5},
  extent={{-40,-30},{40,30}})),__MWORKS(BlockSystem(StateMachine)));
      State avoid 
        annotation (Placement(transformation(origin={82,17},
  extent={{-39,-29.5},{39,29.5}})),__MWORKS(BlockSystem(StateMachine)));
      block State "状态"
        annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state",
         Icon(coordinateSystem(extent={{-100, -100}, {100, 100}},
           grid={2, 2}), graphics={Rectangle(origin = {0, 0},
           lineColor = {74, 84, 154},
           fillColor = {255, 255, 255},
           lineThickness = 1,
           extent = {{-100, 100}, {100, -100}},
           radius = 11), Line(origin = {0, 80},
           points = {{-100, 0}, {100, 0}},
           color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90},
           lineColor = {0, 0, 128},
           extent = {{-100, 10}, {100, -10}},
           textString = "%name",
           textStyle = {TextStyle.None},
           textColor = {0, 0, 128}), Text(origin = {0, -10},
           lineColor = {0, 0, 128},
           extent = {{-100, 90}, {100, -90}},
           textString = "algorithm",
           fontSize = 16,
           textStyle = {TextStyle.None},
           textColor = {0, 0, 128},
           horizontalAlignment = TextAlignment.Left,
           verticalAlignment = TextAlignment.Top)}),
         Diagram(coordinateSystem(extent={{-39,-29.5},{39,29.5}},
  initialScale=1,
  grid={2,2}),graphics = {State(origin={0,0},
  stateTitle=Text(origin={0,0},
  lineColor={74,84,154},
  extent={{-37,21.5},{37,29.5}},
  textString="%name",
  fontSize=16,
  textStyle={TextStyle.Bold},
  textColor={74,84,154},
  horizontalAlignment=TextAlignment.Left),
  stateText=Text(origin={0,0},
  lineColor={74,84,154},
  extent={{-37,-29.5},{37,21.5}},
  textString="%algorithm",
  fontSize=16,
  textColor={74,84,154},
  horizontalAlignment=TextAlignment.Left,
  verticalAlignment=TextAlignment.Top))}),Protection(access=Access.packageDuplicate));
      algorithm
      annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));  speed := 10;
        flag := true;
      end State;
      equation
      initialState(cruise, true, 1) 
      annotation(Line(origin={-374,29},
  points={{0,10},{0,-10}},
  color={113,119,170},
  smooth=Smooth.Bezier),Text(origin={0,0},
  lineColor={74,84,154},
  extent={{0,-3},{0,3}},
  textString="%condition",
  fontSize=10,
  textStyle={TextStyle.Bold},
  textColor={74,84,154}), displayText = "[true]",__MWORKS(BlockSystem(StateMachine(outerTransition=false))));
      transition(cruise, avoid, df <= mindis or dl <= 5 or dr <= 5, reset = false) 
      annotation(Line(origin={-277,2.8644},
      points={{-41,0},{41,0}},
      color={113,119,170},
      smooth=Smooth.Bezier),Text(origin={-28.1093,6.20548},
      lineColor={74,84,154},
      extent={{0,-3},{0,3}},
      textString="%condition",
      fontSize=10,
      textStyle={TextStyle.Bold},
      textColor={74,84,154},
      horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true, comment = false))), displayText ="[df <= mindis or dl <= 5 or dr <= 5]");
      transition(avoid, cruise, df > safeF and dl > safeFLR and dr > safeFLR, reset = false) 
      annotation(Line(origin={-277,-17.9234},
      points={{41,0},{-41,0}},
      color={113,119,170},
      smooth=Smooth.Bezier),Text(origin={-38.9689,-6.89823},
      lineColor={74,84,154},
      extent={{0,-3},{0,3}},
      textString="%condition",
      fontSize=10,
      textStyle={TextStyle.Bold},
      textColor={74,84,154},
      horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true, comment = false))), displayText ="[df > safeF and dl > safeFLR and dr > safeFLR]");
      transition(avoid, cruise, dfl < mindis, reset = false, priority = 2) 
      annotation(Line(origin={-277,-32.2483},
      points={{41,0},{-41,-7.10543e-15}},
      color={113,119,170},
      smooth=Smooth.Bezier),Text(origin={-6.48672,-2.96536},
      lineColor={74,84,154},
      extent={{0,-3},{0,3}},
      textString="%condition",
      fontSize=10,
      textStyle={TextStyle.Bold},
      textColor={74,84,154},
      horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true, comment = false))), displayText ="[dfl < mindis]");
    end State;
    block State1 "状态"
      annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),StateMachine),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state",
       Icon(coordinateSystem(extent={{-100, -100}, {100, 100}},
         grid={2, 2}), graphics={Rectangle(origin = {0, 0},
         lineColor = {74, 84, 154},
         fillColor = {255, 255, 255},
         lineThickness = 1,
         extent = {{-100, 100}, {100, -100}},
         radius = 11), Line(origin = {0, 80},
         points = {{-100, 0}, {100, 0}},
         color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90},
         lineColor = {0, 0, 128},
         extent = {{-100, 10}, {100, -10}},
         textString = "%name",
         textStyle = {TextStyle.None},
         textColor = {0, 0, 128}), Text(origin = {0, -10},
         lineColor = {0, 0, 128},
         extent = {{-100, 90}, {100, -90}},
         textString = "algorithm",
         fontSize = 16,
         textStyle = {TextStyle.None},
         textColor = {0, 0, 128},
         horizontalAlignment = TextAlignment.Left,
         verticalAlignment = TextAlignment.Top)}),
       Diagram(coordinateSystem(extent={{-379,-138},{379,138}},
initialScale=1,
grid={2,2}),graphics = {State(origin={0,0},
stateTitle=Text(origin={0,0},
lineColor={74,84,154},
extent={{-377,130},{377,138}},
textString="%name",
fontSize=16,
textStyle={TextStyle.Bold},
textColor={74,84,154},
horizontalAlignment=TextAlignment.Left),
stateText=Text(origin={0,0},
lineColor={74,84,154},
extent={{-377,-138},{377,130}},
textString="%algorithm",
fontSize=16,
textColor={74,84,154},
horizontalAlignment=TextAlignment.Left,
verticalAlignment=TextAlignment.Top))}),Protection(access=Access.packageDuplicate));
      block State "状态"
        annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state",
         Icon(coordinateSystem(extent={{-100, -100}, {100, 100}},
           grid={2, 2}), graphics={Rectangle(origin = {0, 0},
           lineColor = {74, 84, 154},
           fillColor = {255, 255, 255},
           lineThickness = 1,
           extent = {{-100, 100}, {100, -100}},
           radius = 11), Line(origin = {0, 80},
           points = {{-100, 0}, {100, 0}},
           color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90},
           lineColor = {0, 0, 128},
           extent = {{-100, 10}, {100, -10}},
           textString = "%name",
           textStyle = {TextStyle.None},
           textColor = {0, 0, 128}), Text(origin = {0, -10},
           lineColor = {0, 0, 128},
           extent = {{-100, 90}, {100, -90}},
           textString = "algorithm",
           fontSize = 16,
           textStyle = {TextStyle.None},
           textColor = {0, 0, 128},
           horizontalAlignment = TextAlignment.Left,
           verticalAlignment = TextAlignment.Top)}),
         Diagram(coordinateSystem(extent={{-166,-92},{166,92}},
        initialScale=1,
        grid={2,2}),graphics = {State(origin={0,0},
        stateTitle=Text(origin={0,0},
        lineColor={74,84,154},
        extent={{-164,84},{164,92}},
        textString="%name",
        fontSize=16,
        textStyle={TextStyle.Bold},
        textColor={74,84,154},
        horizontalAlignment=TextAlignment.Left),
        stateText=Text(origin={0,0},
        lineColor={74,84,154},
        extent={{-164,-92},{164,84}},
        textString="%algorithm",
        fontSize=16,
        textColor={74,84,154},
        horizontalAlignment=TextAlignment.Left,
        verticalAlignment=TextAlignment.Top))}),Protection(access=Access.packageDuplicate));
        block State "状态"
          annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state",
           Icon(coordinateSystem(extent={{-100, -100}, {100, 100}},
             grid={2, 2}), graphics={Rectangle(origin = {0, 0},
             lineColor = {74, 84, 154},
             fillColor = {255, 255, 255},
             lineThickness = 1,
             extent = {{-100, 100}, {100, -100}},
             radius = 11), Line(origin = {0, 80},
             points = {{-100, 0}, {100, 0}},
             color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90},
             lineColor = {0, 0, 128},
             extent = {{-100, 10}, {100, -10}},
             textString = "%name",
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128}), Text(origin = {0, -10},
             lineColor = {0, 0, 128},
             extent = {{-100, 90}, {100, -90}},
             textString = "algorithm",
             fontSize = 16,
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128},
             horizontalAlignment = TextAlignment.Left,
             verticalAlignment = TextAlignment.Top)}),
           Diagram(coordinateSystem(extent={{-24,-19.5},{24,19.5}},
          initialScale=1,
          grid={2,2}),graphics = {State(origin={0,0},
          stateTitle=Text(origin={0,0},
          lineColor={74,84,154},
          extent={{-22,11.5},{22,19.5}},
          textString="%name",
          fontSize=16,
          textStyle={TextStyle.Bold},
          textColor={74,84,154},
          horizontalAlignment=TextAlignment.Left),
          stateText=Text(origin={0,0},
          lineColor={74,84,154},
          extent={{-22,-19.5},{22,11.5}},
          textString="%algorithm",
          fontSize=16,
          textColor={74,84,154},
          horizontalAlignment=TextAlignment.Left,
          verticalAlignment=TextAlignment.Top),
          stateLine = Line(origin={0,0},
          color = {74, 84, 154},
          points={{-40,22},{40,22}}))}),Protection(access=Access.packageDuplicate));
        algorithm
        annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));  steer := 0;
        end State;
        State ini_state 
          annotation (Placement(transformation(origin={-84,50},
  extent={{-24,-19.5},{24,19.5}})),__MWORKS(BlockSystem(StateMachine)));
        State1 turn_right 
          annotation (Placement(transformation(origin={97,-44},
  extent={{-53,-20},{53,20}})),__MWORKS(BlockSystem(StateMachine)));
        State2 turn_left 
          annotation (Placement(transformation(origin={-81,-46},
  extent={{-51,-20},{51,20}})),__MWORKS(BlockSystem(StateMachine)));
        block State1 "状态"
          annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state",
           Icon(coordinateSystem(extent={{-100, -100}, {100, 100}},
             grid={2, 2}), graphics={Rectangle(origin = {0, 0},
             lineColor = {74, 84, 154},
             fillColor = {255, 255, 255},
             lineThickness = 1,
             extent = {{-100, 100}, {100, -100}},
             radius = 11), Line(origin = {0, 80},
             points = {{-100, 0}, {100, 0}},
             color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90},
             lineColor = {0, 0, 128},
             extent = {{-100, 10}, {100, -10}},
             textString = "%name",
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128}), Text(origin = {0, -10},
             lineColor = {0, 0, 128},
             extent = {{-100, 90}, {100, -90}},
             textString = "algorithm",
             fontSize = 16,
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128},
             horizontalAlignment = TextAlignment.Left,
             verticalAlignment = TextAlignment.Top)}),
           Diagram(coordinateSystem(extent={{-53,-20},{53,20}},
          initialScale=1,
          grid={2,2}),graphics = {State(origin={0,0},
          stateTitle=Text(origin={0,0},
          lineColor={74,84,154},
          extent={{-51,12},{51,20}},
          textString="%name",
          fontSize=16,
          textStyle={TextStyle.Bold},
          textColor={74,84,154},
          horizontalAlignment=TextAlignment.Left),
          stateText=Text(origin={0,0},
          lineColor={74,84,154},
          extent={{-51,-20},{51,12}},
          textString="%algorithm",
          fontSize=16,
          textColor={74,84,154},
          horizontalAlignment=TextAlignment.Left,
          verticalAlignment=TextAlignment.Top),
          stateLine = Line(origin={0,0},
          color = {74, 84, 154},
          points={{-40,22},{40,22}}))}),Protection(access=Access.packageDuplicate));
        algorithm
        annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));  steer := 0.6;
        end State1;
        block State2 "状态"
          annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state",
           Icon(coordinateSystem(extent={{-100, -100}, {100, 100}},
             grid={2, 2}), graphics={Rectangle(origin = {0, 0},
             lineColor = {74, 84, 154},
             fillColor = {255, 255, 255},
             lineThickness = 1,
             extent = {{-100, 100}, {100, -100}},
             radius = 11), Line(origin = {0, 80},
             points = {{-100, 0}, {100, 0}},
             color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90},
             lineColor = {0, 0, 128},
             extent = {{-100, 10}, {100, -10}},
             textString = "%name",
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128}), Text(origin = {0, -10},
             lineColor = {0, 0, 128},
             extent = {{-100, 90}, {100, -90}},
             textString = "algorithm",
             fontSize = 16,
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128},
             horizontalAlignment = TextAlignment.Left,
             verticalAlignment = TextAlignment.Top)}),
           Diagram(coordinateSystem(extent={{-51,-20},{51,20}},
          initialScale=1,
          grid={2,2}),graphics = {State(origin={0,0},
          stateTitle=Text(origin={0,0},
          lineColor={74,84,154},
          extent={{-49,12},{49,20}},
          textString="%name",
          fontSize=16,
          textStyle={TextStyle.Bold},
          textColor={74,84,154},
          horizontalAlignment=TextAlignment.Left),
          stateText=Text(origin={0,0},
          lineColor={74,84,154},
          extent={{-49,-20},{49,12}},
          textString="%algorithm",
          fontSize=16,
          textColor={74,84,154},
          horizontalAlignment=TextAlignment.Left,
          verticalAlignment=TextAlignment.Top),
          stateLine = Line(origin={0,0},
          color = {74, 84, 154},
          points={{-40,22},{40,22}}))}),Protection(access=Access.packageDuplicate));
        algorithm
        annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));  steer := -0.6;
        end State2;
      equation
        transition(ini_state, turn_left, dl - dr > mindis, reset = false) 
        annotation(Line(origin={-293.806,-271.75},
points={{0,28.25},{0,-28.25}},
color={113,119,170},
smooth=Smooth.Bezier),Text(origin={-28.0109,-4.46722},
lineColor={74,84,154},
extent={{0,-3},{0,3}},
textString="%condition",
fontSize=10,
textStyle={TextStyle.Bold},
textColor={74,84,154},
horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition=true))), displayText ="[dl - dr > mindis]");
        transition(turn_left, ini_state, dl - dr <= mindis, reset = false) 
        annotation(Line(origin={-306.027,-271.75},
points={{0,-28.25},{0,28.25}},
color={113,119,170},
smooth=Smooth.Bezier),Text(origin={-30.7073,14.5007},
lineColor={74,84,154},
extent={{0,-3},{0,3}},
textString="%condition",
fontSize=10,
textStyle={TextStyle.Bold},
textColor={74,84,154},
horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition=true))), displayText ="[dl - dr <= mindis]");
        transition(turn_right, ini_state, dr - dl <= mindis, reset = false) 
        annotation(Line(origin={-184.29,-246.814},
points={{37.4113,-51.186},{-81.71,6.88737}},
color={113,119,170},
smooth=Smooth.Bezier),Text(origin={-36.5955,-7.88489},
lineColor={74,84,154},
extent={{0,-3},{0,3}},
textString="%condition",
fontSize=10,
textStyle={TextStyle.Bold},
textColor={74,84,154},
horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition=true))), displayText ="[dr - dl <= mindis]");
        initialState(ini_state, true, 1) 
        annotation(Line(origin={-289.974,-199.673},
points={{0,4.82698},{0,-4.82698}},
color={113,119,170},
smooth=Smooth.Bezier),Text(origin={0,0},
lineColor={74,84,154},
extent={{0,-3},{0,3}},
textString="%condition",
fontSize=10,
textStyle={TextStyle.Bold},
textColor={74,84,154}), displayText = "[true]",__MWORKS(BlockSystem(StateMachine(outerTransition=false))));
        transition(ini_state, turn_right, dr - dl > mindis, reset = false, priority = 2) 
        annotation(Line(origin={-166.081,-235.84},
points={{-99.919,8.13366},{45.8927,-62.16}},
color={113,119,170},
smooth=Smooth.Bezier),Text(origin={-24.6651,0.00790729},
lineColor={74,84,154},
extent={{0,-3},{0,3}},
textString="%condition",
fontSize=10,
textStyle={TextStyle.Bold},
textColor={74,84,154},
horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition=true))), displayText ="[dr - dl > mindis]");
        transition(ini_state, turn_right, dl <= safeFLR, reset = false, priority = 3) 
        annotation(Line(origin={-147.064,-226.264},
        points={{-118.936,8.17864},{55.3787,-71.735975}},
        color={113,119,170},
        smooth=Smooth.Bezier),Text(origin={-1.80962,-2.48822},
        lineColor={74,84,154},
        extent={{0,-3},{0,3}},
        textString="%condition",
        fontSize=10,
        textStyle={TextStyle.Bold},
        textColor={74,84,154},
        horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true, comment = false))), displayText ="[dl <= safeFLR]");
        transition(ini_state, turn_left, dr <= safeFLR, reset = false, priority = 4) 
        annotation(Line(origin={-281.586,-271.75},
        points={{0,28.25},{0,-28.25}},
        color={113,119,170},
        smooth=Smooth.Bezier),Text(origin={2.71443,-16.739},
        lineColor={74,84,154},
        extent={{0,-3},{0,3}},
        textString="%condition",
        fontSize=10,
        textStyle={TextStyle.Bold},
        textColor={74,84,154},
        horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true, comment = false))), displayText ="[dr <= safeFLR]");
      end State;
      State curise_lateral 
      annotation(Placement(transformation(origin={-177,-10},
extent={{-166,-92},{166,92}})),__MWORKS(BlockSystem(StateMachine)));
      State1 avoid_lateral 
        annotation (Placement(transformation(origin={179,-8},
extent={{-168,-92},{168,92}})),__MWORKS(BlockSystem(StateMachine)));
      block State1 "状态"
        annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state, SampleTime(auto = true)),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state",
         Icon(coordinateSystem(extent={{-100, -100}, {100, 100}},
           grid={2, 2}), graphics={Rectangle(origin = {0, 0},
           lineColor = {74, 84, 154},
           fillColor = {255, 255, 255},
           lineThickness = 1,
           extent = {{-100, 100}, {100, -100}},
           radius = 11), Line(origin = {0, 80},
           points = {{-100, 0}, {100, 0}},
           color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90},
           lineColor = {0, 0, 128},
           extent = {{-100, 10}, {100, -10}},
           textString = "%name",
           textStyle = {TextStyle.None},
           textColor = {0, 0, 128}), Text(origin = {0, -10},
           lineColor = {0, 0, 128},
           extent = {{-100, 90}, {100, -90}},
           textString = "algorithm",
           fontSize = 16,
           textStyle = {TextStyle.None},
           textColor = {0, 0, 128},
           horizontalAlignment = TextAlignment.Left,
           verticalAlignment = TextAlignment.Top)}),
         Diagram(coordinateSystem(extent={{-168,-92},{168,92}},
        initialScale=1,
        grid={2,2}),graphics = {State(origin={0,0},
        stateTitle=Text(origin={0,0},
        lineColor={74,84,154},
        extent={{-166,84},{166,92}},
        textString="%name",
        fontSize=16,
        textStyle={TextStyle.Bold},
        textColor={74,84,154},
        horizontalAlignment=TextAlignment.Left),
        stateText=Text(origin={0,0},
        lineColor={74,84,154},
        extent={{-166,-92},{166,84}},
        textString="%algorithm",
        fontSize=16,
        textColor={74,84,154},
        horizontalAlignment=TextAlignment.Left,
        verticalAlignment=TextAlignment.Top),
        stateLine = Line(origin={0,0},
        color = {74, 84, 154},
        points={{-40,22},{40,22}}))}),Protection(access=Access.packageDuplicate));
        block State "状态"
          annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state",
           Icon(coordinateSystem(extent={{-100, -100}, {100, 100}},
             grid={2, 2}), graphics={Rectangle(origin = {0, 0},
             lineColor = {74, 84, 154},
             fillColor = {255, 255, 255},
             lineThickness = 1,
             extent = {{-100, 100}, {100, -100}},
             radius = 11), Line(origin = {0, 80},
             points = {{-100, 0}, {100, 0}},
             color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90},
             lineColor = {0, 0, 128},
             extent = {{-100, 10}, {100, -10}},
             textString = "%name",
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128}), Text(origin = {0, -10},
             lineColor = {0, 0, 128},
             extent = {{-100, 90}, {100, -90}},
             textString = "algorithm",
             fontSize = 16,
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128},
             horizontalAlignment = TextAlignment.Left,
             verticalAlignment = TextAlignment.Top)}),
           Diagram(coordinateSystem(extent={{-29,-18},{29,18}},
          initialScale=1,
          grid={2,2}),graphics = {State(origin={0,0},
          stateTitle=Text(origin={0,0},
          lineColor={74,84,154},
          extent={{-27,10},{27,18}},
          textString="%name",
          fontSize=16,
          textStyle={TextStyle.Bold},
          textColor={74,84,154},
          horizontalAlignment=TextAlignment.Left),
          stateText=Text(origin={0,0},
          lineColor={74,84,154},
          extent={{-27,-18},{27,10}},
          textString="%algorithm",
          fontSize=16,
          textColor={74,84,154},
          horizontalAlignment=TextAlignment.Left,
          verticalAlignment=TextAlignment.Top),
          stateLine = Line(origin={0,0},
          color = {74, 84, 154},
          points={{-40,22},{40,22}}))}),Protection(access=Access.packageDuplicate));
        algorithm
        annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));  steer := 0;
        end State;
        State ini_state 
          annotation (Placement(transformation(origin={-107,36},
  extent={{-29,-18},{29,18}})),__MWORKS(BlockSystem(StateMachine)));
        State1 turn_left 
        annotation(Placement(transformation(origin={-101,-46},
  extent={{-51,-20},{51,20}})),__MWORKS(BlockSystem(StateMachine)));
        State2 turn_right 
        annotation(Placement(transformation(origin={69,-46},
  extent={{-53,-20},{53,20}})),__MWORKS(BlockSystem(StateMachine)));
        block State1 "状态"
          annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state",
           Icon(coordinateSystem(extent={{-100, -100}, {100, 100}},
             grid={2, 2}), graphics={Rectangle(origin = {0, 0},
             lineColor = {74, 84, 154},
             fillColor = {255, 255, 255},
             lineThickness = 1,
             extent = {{-100, 100}, {100, -100}},
             radius = 11), Line(origin = {0, 80},
             points = {{-100, 0}, {100, 0}},
             color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90},
             lineColor = {0, 0, 128},
             extent = {{-100, 10}, {100, -10}},
             textString = "%name",
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128}), Text(origin = {0, -10},
             lineColor = {0, 0, 128},
             extent = {{-100, 90}, {100, -90}},
             textString = "algorithm",
             fontSize = 16,
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128},
             horizontalAlignment = TextAlignment.Left,
             verticalAlignment = TextAlignment.Top)}),
           Diagram(coordinateSystem(extent={{-51,-20},{51,20}},
          initialScale=1,
          grid={2,2}),graphics = {State(origin={0,0},
          stateTitle=Text(origin={0,0},
          lineColor={74,84,154},
          extent={{-49,12},{49,20}},
          textString="%name",
          fontSize=16,
          textStyle={TextStyle.Bold},
          textColor={74,84,154},
          horizontalAlignment=TextAlignment.Left),
          stateText=Text(origin={0,0},
          lineColor={74,84,154},
          extent={{-49,-20},{49,12}},
          textString="%algorithm",
          fontSize=16,
          textColor={74,84,154},
          horizontalAlignment=TextAlignment.Left,
          verticalAlignment=TextAlignment.Top),
          stateLine = Line(origin={0,0},
          color = {74, 84, 154},
          points={{-40,22},{40,22}}))}),Protection(access=Access.packageDuplicate));
        algorithm
        annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));  steer := -0.6;
        end State1;
        block State2 "状态"
          annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state",
           Icon(coordinateSystem(extent={{-100, -100}, {100, 100}},
             grid={2, 2}), graphics={Rectangle(origin = {0, 0},
             lineColor = {74, 84, 154},
             fillColor = {255, 255, 255},
             lineThickness = 1,
             extent = {{-100, 100}, {100, -100}},
             radius = 11), Line(origin = {0, 80},
             points = {{-100, 0}, {100, 0}},
             color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90},
             lineColor = {0, 0, 128},
             extent = {{-100, 10}, {100, -10}},
             textString = "%name",
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128}), Text(origin = {0, -10},
             lineColor = {0, 0, 128},
             extent = {{-100, 90}, {100, -90}},
             textString = "algorithm",
             fontSize = 16,
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128},
             horizontalAlignment = TextAlignment.Left,
             verticalAlignment = TextAlignment.Top)}),
           Diagram(coordinateSystem(extent={{-53,-20},{53,20}},
          initialScale=1,
          grid={2,2}),graphics = {State(origin={0,0},
          stateTitle=Text(origin={0,0},
          lineColor={74,84,154},
          extent={{-51,12},{51,20}},
          textString="%name",
          fontSize=16,
          textStyle={TextStyle.Bold},
          textColor={74,84,154},
          horizontalAlignment=TextAlignment.Left),
          stateText=Text(origin={0,0},
          lineColor={74,84,154},
          extent={{-51,-20},{51,12}},
          textString="%algorithm",
          fontSize=16,
          textColor={74,84,154},
          horizontalAlignment=TextAlignment.Left,
          verticalAlignment=TextAlignment.Top),
          stateLine = Line(origin={0,0},
          color = {74, 84, 154},
          points={{-40,22},{40,22}}))}),Protection(access=Access.packageDuplicate));
        algorithm
        annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));  steer := 0.4;
        end State2;
      equation
        transition(ini_state, turn_left, dl <= safeFLR, reset = false) 
        annotation(Line(origin={27.3006,-276},
        points={{3.55271e-15,22},{-3.55271e-15,-22}},
        color={113,119,170},
        smooth=Smooth.Bezier),Text(origin={3.15746,-1.93588},
        lineColor={74,84,154},
        extent={{0,-3},{0,3}},
        textString="%condition",
        fontSize=10,
        textStyle={TextStyle.Bold},
        textColor={74,84,154},
        horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true, comment = false))), displayText ="[dl <= safeFLR]");
        initialState(ini_state, true, 1) 
        annotation(Line(origin={38,-208},
points={{0,10},{0,-10}},
color={113,119,170},
smooth=Smooth.Bezier),Text(origin={0,0},
lineColor={74,84,154},
extent={{0,-3},{0,3}},
textString="%condition",
fontSize=10,
textStyle={TextStyle.Bold},
textColor={74,84,154}), displayText = "[true]",__MWORKS(BlockSystem(StateMachine(outerTransition=false))));
        transition(ini_state, turn_right, dr <= safeFLR, reset = false, priority = 2) 
        annotation(Line(origin={150.092,-245.509},
        points={{-78.0922,8.96324},{34.5644875,-52.491}},
        color={113,119,170},
        smooth=Smooth.Bezier),Text(origin={0,0},
        lineColor={74,84,154},
        extent={{0,-3},{0,3}},
        textString="%condition",
        fontSize=10,
        textStyle={TextStyle.Bold},
        textColor={74,84,154},
        horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true, comment = false))), displayText ="[dr <= safeFLR]");
      end State1;
    equation
      transition(avoid_lateral, curise_lateral, not flag, reset = false) 
      annotation(Line(origin={-30.2029,-148.623},
points={{69.1344,-31.377},{0.129678,0.00178017},{-68.7286,-33.377}},
color={113,119,170},
smooth=Smooth.Bezier),Text(origin={-7.15991,7.15991},
lineColor={74,84,154},
extent={{0,-3},{0,3}},
textString="%condition",
fontSize=10,
textStyle={TextStyle.Bold},
textColor={74,84,154},
horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition=true))), displayText = "[not flag]");
      transition(curise_lateral, avoid_lateral, flag, reset = false) 
      annotation(Line(origin={-30,-165.017},
points={{-30.9664,-16.9832},{30.9664,-14.9832}},
color={113,119,170},
smooth=Smooth.Bezier),Text(origin={0,0},
lineColor={74,84,154},
extent={{0,-3},{0,3}},
textString="%condition",
fontSize=10,
textStyle={TextStyle.Bold},
textColor={74,84,154},
horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition=true))), displayText = "[flag]");
      initialState(curise_lateral, true, 1) 
      annotation(Line(origin={-241.907,-170.981},
points={{0.0362665,14.1629},{-7.78976e-5,1.08241},{0.0362665,-11.0189}},
color={113,119,170},
smooth=Smooth.Bezier),Text(origin={-12.7065,1.36141},
lineColor={74,84,154},
extent={{0,-3},{0,3}},
textString="%condition",
fontSize=10,
textStyle={TextStyle.Bold},
textColor={74,84,154}), displayText = "[true]",__MWORKS(BlockSystem(StateMachine(outerTransition=false))));
    end State1;
    block State2 "状态"
      annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state",
       Icon(coordinateSystem(extent={{-100, -100}, {100, 100}},
         grid={2, 2}), graphics={Rectangle(origin = {0, 0},
         lineColor = {74, 84, 154},
         fillColor = {255, 255, 255},
         lineThickness = 1,
         extent = {{-100, 100}, {100, -100}},
         radius = 11), Line(origin = {0, 80},
         points = {{-100, 0}, {100, 0}},
         color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90},
         lineColor = {0, 0, 128},
         extent = {{-100, 10}, {100, -10}},
         textString = "%name",
         textStyle = {TextStyle.None},
         textColor = {0, 0, 128}), Text(origin = {0, -10},
         lineColor = {0, 0, 128},
         extent = {{-100, 90}, {100, -90}},
         textString = "algorithm",
         fontSize = 16,
         textStyle = {TextStyle.None},
         textColor = {0, 0, 128},
         horizontalAlignment = TextAlignment.Left,
         verticalAlignment = TextAlignment.Top)}),
       Diagram(coordinateSystem(extent={{-245.5,-90.5},{245.5,90.5}},
initialScale=1,
grid={2,2}),graphics = {State(origin={0,0},
stateTitle=Text(origin={0,0},
lineColor={74,84,154},
extent={{-243.5,82.5},{243.5,90.5}},
textString="%name",
fontSize=16,
textStyle={TextStyle.Bold},
textColor={74,84,154},
horizontalAlignment=TextAlignment.Left),
stateText=Text(origin={0,0},
lineColor={74,84,154},
extent={{-243.5,-90.5},{243.5,82.5}},
textString="%algorithm",
fontSize=16,
textColor={74,84,154},
horizontalAlignment=TextAlignment.Left,
verticalAlignment=TextAlignment.Top))}),Protection(access=Access.packageDuplicate));
      State3 cruise 
        annotation (Placement(transformation(origin={-126.5,6.66134e-15},
extent={{-78,-50},{78,50}})),__MWORKS(BlockSystem(StateMachine)));
      State avoid 
        annotation (Placement(transformation(origin={114.5,-7.10543e-15},
extent={{-81,-50},{81,50}})),__MWORKS(BlockSystem(StateMachine)));
      block State3 "状态"
        annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state, SampleTime(auto = true)),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state",
         Icon(coordinateSystem(extent={{-100, -100}, {100, 100}},
           grid={2, 2}), graphics={Rectangle(origin = {0, 0},
           lineColor = {74, 84, 154},
           fillColor = {255, 255, 255},
           lineThickness = 1,
           extent = {{-100, 100}, {100, -100}},
           radius = 11), Line(origin = {0, 80},
           points = {{-100, 0}, {100, 0}},
           color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90},
           lineColor = {0, 0, 128},
           extent = {{-100, 10}, {100, -10}},
           textString = "%name",
           textStyle = {TextStyle.None},
           textColor = {0, 0, 128}), Text(origin = {0, -10},
           lineColor = {0, 0, 128},
           extent = {{-100, 90}, {100, -90}},
           textString = "algorithm",
           fontSize = 16,
           textStyle = {TextStyle.None},
           textColor = {0, 0, 128},
           horizontalAlignment = TextAlignment.Left,
           verticalAlignment = TextAlignment.Top)}),
         Diagram(coordinateSystem(extent={{-78,-50},{78,50}},
  initialScale=1,
  grid={2,2}),graphics = {State(origin={0,0},
  stateTitle=Text(origin={0,0},
  lineColor={74,84,154},
  extent={{-76,42},{76,50}},
  textString="%name",
  fontSize=16,
  textStyle={TextStyle.Bold},
  textColor={74,84,154},
  horizontalAlignment=TextAlignment.Left),
  stateText=Text(origin={0,0},
  lineColor={74,84,154},
  extent={{-76,-50},{76,42}},
  textString="%algorithm",
  fontSize=16,
  textColor={74,84,154},
  horizontalAlignment=TextAlignment.Left,
  verticalAlignment=TextAlignment.Top),
  stateLine = Line(origin={0,0},
  color = {74, 84, 154},
  points={{-40,22},{40,22}}))}),Protection(access=Access.packageDuplicate));
        block State "状态"
          annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state",
           Icon(coordinateSystem(extent={{-100, -100}, {100, 100}},
             grid={2, 2}), graphics={Rectangle(origin = {0, 0},
             lineColor = {74, 84, 154},
             fillColor = {255, 255, 255},
             lineThickness = 1,
             extent = {{-100, 100}, {100, -100}},
             radius = 11), Line(origin = {0, 80},
             points = {{-100, 0}, {100, 0}},
             color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90},
             lineColor = {0, 0, 128},
             extent = {{-100, 10}, {100, -10}},
             textString = "%name",
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128}), Text(origin = {0, -10},
             lineColor = {0, 0, 128},
             extent = {{-100, 90}, {100, -90}},
             textString = "algorithm",
             fontSize = 16,
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128},
             horizontalAlignment = TextAlignment.Left,
             verticalAlignment = TextAlignment.Top)}),
           Diagram(coordinateSystem(extent={{-20.5,-14.25},{20.5,14.25}},
        initialScale=1,
        grid={2,2}),graphics = {State(origin={0,0},
        stateTitle=Text(origin={0,0},
        lineColor={74,84,154},
        extent={{-18.5,6.25},{18.5,14.25}},
        textString="%name",
        fontSize=16,
        textStyle={TextStyle.Bold},
        textColor={74,84,154},
        horizontalAlignment=TextAlignment.Left),
        stateText=Text(origin={0,0},
        lineColor={74,84,154},
        extent={{-18.5,-14.25},{18.5,6.25}},
        textString="%algorithm",
        fontSize=16,
        textColor={74,84,154},
        horizontalAlignment=TextAlignment.Left,
        verticalAlignment=TextAlignment.Top))}),Protection(access=Access.packageDuplicate));
        algorithm
        annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));gapS := 0;
        end State;
        State state 
        annotation(Placement(transformation(origin={-42.5,-1.5},
        extent={{-20.5,-14.25},{20.5,14.25}})),__MWORKS(BlockSystem(StateMachine)));
        State1 turn_right 
        annotation(Placement(transformation(origin={44.5,-23},
        extent={{-19.5,-17},{19.5,17}})),__MWORKS(BlockSystem(StateMachine)));
        State2 turn_left 
        annotation(Placement(transformation(origin={45,20},
        extent={{-19,-17},{19,17}})),__MWORKS(BlockSystem(StateMachine)));
        block State1 "状态"
          annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state",
           Icon(coordinateSystem(extent={{-100, -100}, {100, 100}},
             grid={2, 2}), graphics={Rectangle(origin = {0, 0},
             lineColor = {74, 84, 154},
             fillColor = {255, 255, 255},
             lineThickness = 1,
             extent = {{-100, 100}, {100, -100}},
             radius = 11), Line(origin = {0, 80},
             points = {{-100, 0}, {100, 0}},
             color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90},
             lineColor = {0, 0, 128},
             extent = {{-100, 10}, {100, -10}},
             textString = "%name",
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128}), Text(origin = {0, -10},
             lineColor = {0, 0, 128},
             extent = {{-100, 90}, {100, -90}},
             textString = "algorithm",
             fontSize = 16,
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128},
             horizontalAlignment = TextAlignment.Left,
             verticalAlignment = TextAlignment.Top)}),
           Diagram(coordinateSystem(extent={{-19.5,-17},{19.5,17}},
        initialScale=1,
        grid={2,2}),graphics = {State(origin={0,0},
        stateTitle=Text(origin={0,0},
        lineColor={74,84,154},
        extent={{-17.5,9},{17.5,17}},
        textString="%name",
        fontSize=16,
        textStyle={TextStyle.Bold},
        textColor={74,84,154},
        horizontalAlignment=TextAlignment.Left),
        stateText=Text(origin={0,0},
        lineColor={74,84,154},
        extent={{-17.5,-17},{17.5,9}},
        textString="%algorithm",
        fontSize=16,
        textColor={74,84,154},
        horizontalAlignment=TextAlignment.Left,
        verticalAlignment=TextAlignment.Top),
        stateLine = Line(origin={0,0},
        color = {74, 84, 154},
        points={{-40,22},{40,22}}))}),Protection(access=Access.packageDuplicate));
        algorithm
        annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));  gapS := -5;
        end State1;
        block State2 "状态"
          annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state",
           Icon(coordinateSystem(extent={{-100, -100}, {100, 100}},
             grid={2, 2}), graphics={Rectangle(origin = {0, 0},
             lineColor = {74, 84, 154},
             fillColor = {255, 255, 255},
             lineThickness = 1,
             extent = {{-100, 100}, {100, -100}},
             radius = 11), Line(origin = {0, 80},
             points = {{-100, 0}, {100, 0}},
             color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90},
             lineColor = {0, 0, 128},
             extent = {{-100, 10}, {100, -10}},
             textString = "%name",
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128}), Text(origin = {0, -10},
             lineColor = {0, 0, 128},
             extent = {{-100, 90}, {100, -90}},
             textString = "algorithm",
             fontSize = 16,
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128},
             horizontalAlignment = TextAlignment.Left,
             verticalAlignment = TextAlignment.Top)}),
           Diagram(coordinateSystem(extent={{-19,-17},{19,17}},
        initialScale=1,
        grid={2,2}),graphics = {State(origin={0,0},
        stateTitle=Text(origin={0,0},
        lineColor={74,84,154},
        extent={{-17,9},{17,17}},
        textString="%name",
        fontSize=16,
        textStyle={TextStyle.Bold},
        textColor={74,84,154},
        horizontalAlignment=TextAlignment.Left),
        stateText=Text(origin={0,0},
        lineColor={74,84,154},
        extent={{-17,-17},{17,9}},
        textString="%algorithm",
        fontSize=16,
        textColor={74,84,154},
        horizontalAlignment=TextAlignment.Left,
        verticalAlignment=TextAlignment.Top),
        stateLine = Line(origin={0,0},
        color = {74, 84, 154},
        points={{-40,22},{40,22}}))}),Protection(access=Access.packageDuplicate));
        algorithm
        annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));  gapS := 5;
        end State2;
      equation
        initialState(state, true, 1) 
        annotation(Line(origin={-77.6507,-4.7109},
points={{0,10.0391},{0,-10.0391}},
color={113,119,170},
smooth=Smooth.Bezier),Text(origin={0,0},
lineColor={74,84,154},
extent={{0,-3},{0,3}},
textString="%condition",
fontSize=10,
textStyle={TextStyle.Bold},
textColor={74,84,154}), displayText = "[true]",__MWORKS(BlockSystem(StateMachine(outerTransition=false))));
        transition(state, turn_right, steer > 0, reset = false, priority = 2) 
        annotation(Line(origin={-20.5,-45.0222},
points={{-23.5,11.2754},{23.5,-11.2754}},
color={113,119,170},
smooth=Smooth.Bezier),Text(origin={-5.54773,5.41242},
lineColor={74,84,154},
extent={{0,-3},{0,3}},
textString="%condition",
fontSize=10,
textStyle={TextStyle.Bold},
textColor={74,84,154},
horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition=true))), displayText = "[steer > 0]");
        transition(state, turn_left, steer < 0, reset = false) 
        annotation(Line(origin={-20,-15.2996},
points={{-24,-9.04194},{24,9.04194}},
color={113,119,170},
smooth=Smooth.Bezier),Text(origin={-5.40295,6.48354},
lineColor={74,84,154},
extent={{0,-3},{0,3}},
textString="%condition",
fontSize=10,
textStyle={TextStyle.Bold},
textColor={74,84,154},
horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition=true))), displayText = "[steer < 0]");
      end State3;
      block State "状态"
        annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state, SampleTime(auto = true)),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state",
         Icon(coordinateSystem(extent={{-100, -100}, {100, 100}},
           grid={2, 2}), graphics={Rectangle(origin = {0, 0},
           lineColor = {74, 84, 154},
           fillColor = {255, 255, 255},
           lineThickness = 1,
           extent = {{-100, 100}, {100, -100}},
           radius = 11), Line(origin = {0, 80},
           points = {{-100, 0}, {100, 0}},
           color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90},
           lineColor = {0, 0, 128},
           extent = {{-100, 10}, {100, -10}},
           textString = "%name",
           textStyle = {TextStyle.None},
           textColor = {0, 0, 128}), Text(origin = {0, -10},
           lineColor = {0, 0, 128},
           extent = {{-100, 90}, {100, -90}},
           textString = "algorithm",
           fontSize = 16,
           textStyle = {TextStyle.None},
           textColor = {0, 0, 128},
           horizontalAlignment = TextAlignment.Left,
           verticalAlignment = TextAlignment.Top)}),
         Diagram(coordinateSystem(extent={{-81,-50},{81,50}},
  initialScale=1,
  grid={2,2}),graphics = {State(origin={0,0},
  stateTitle=Text(origin={0,0},
  lineColor={74,84,154},
  extent={{-79,42},{79,50}},
  textString="%name",
  fontSize=16,
  textStyle={TextStyle.Bold},
  textColor={74,84,154},
  horizontalAlignment=TextAlignment.Left),
  stateText=Text(origin={0,0},
  lineColor={74,84,154},
  extent={{-79,-50},{79,42}},
  textString="%algorithm",
  fontSize=16,
  textColor={74,84,154},
  horizontalAlignment=TextAlignment.Left,
  verticalAlignment=TextAlignment.Top),
  stateLine = Line(origin={0,0},
  color = {74, 84, 154},
  points={{-40,22},{40,22}}))}),Protection(access=Access.packageDuplicate));
        block State3 "状态"
          annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state",
           Icon(coordinateSystem(extent={{-100, -100}, {100, 100}},
             grid={2, 2}), graphics={Rectangle(origin = {0, 0},
             lineColor = {74, 84, 154},
             fillColor = {255, 255, 255},
             lineThickness = 1,
             extent = {{-100, 100}, {100, -100}},
             radius = 11), Line(origin = {0, 80},
             points = {{-100, 0}, {100, 0}},
             color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90},
             lineColor = {0, 0, 128},
             extent = {{-100, 10}, {100, -10}},
             textString = "%name",
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128}), Text(origin = {0, -10},
             lineColor = {0, 0, 128},
             extent = {{-100, 90}, {100, -90}},
             textString = "algorithm",
             fontSize = 16,
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128},
             horizontalAlignment = TextAlignment.Left,
             verticalAlignment = TextAlignment.Top)}),
           Diagram(coordinateSystem(extent={{-20.5,-14.25},{20.5,14.25}},
          initialScale=1,
          grid={2,2}),graphics = {State(origin={0,0},
          stateTitle=Text(origin={0,0},
          lineColor={74,84,154},
          extent={{-18.5,6.25},{18.5,14.25}},
          textString="%name",
          fontSize=16,
          textStyle={TextStyle.Bold},
          textColor={74,84,154},
          horizontalAlignment=TextAlignment.Left),
          stateText=Text(origin={0,0},
          lineColor={74,84,154},
          extent={{-18.5,-14.25},{18.5,6.25}},
          textString="%algorithm",
          fontSize=16,
          textColor={74,84,154},
          horizontalAlignment=TextAlignment.Left,
          verticalAlignment=TextAlignment.Top))}),Protection(access=Access.packageDuplicate));
        algorithm
        annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));  gapS := 0;
        end State3;
        State3 state1 
        annotation(Placement(transformation(origin={-54.5,-1.5},
  extent={{-20.5,-14.25},{20.5,14.25}})),__MWORKS(BlockSystem(StateMachine)));
        State1 turn_left 
        annotation(Placement(transformation(origin={24,20},
  extent={{-19,-17},{19,17}})),__MWORKS(BlockSystem(StateMachine)));
        State2 turn_right 
        annotation(Placement(transformation(origin={25,-26},
  extent={{-19.5,-17},{19.5,17}})),__MWORKS(BlockSystem(StateMachine)));
        block State1 "状态"
          annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state",
           Icon(coordinateSystem(extent={{-100, -100}, {100, 100}},
             grid={2, 2}), graphics={Rectangle(origin = {0, 0},
             lineColor = {74, 84, 154},
             fillColor = {255, 255, 255},
             lineThickness = 1,
             extent = {{-100, 100}, {100, -100}},
             radius = 11), Line(origin = {0, 80},
             points = {{-100, 0}, {100, 0}},
             color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90},
             lineColor = {0, 0, 128},
             extent = {{-100, 10}, {100, -10}},
             textString = "%name",
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128}), Text(origin = {0, -10},
             lineColor = {0, 0, 128},
             extent = {{-100, 90}, {100, -90}},
             textString = "algorithm",
             fontSize = 16,
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128},
             horizontalAlignment = TextAlignment.Left,
             verticalAlignment = TextAlignment.Top)}),
           Diagram(coordinateSystem(extent={{-19,-17},{19,17}},
          initialScale=1,
          grid={2,2}),graphics = {State(origin={0,0},
          stateTitle=Text(origin={0,0},
          lineColor={74,84,154},
          extent={{-17,9},{17,17}},
          textString="%name",
          fontSize=16,
          textStyle={TextStyle.Bold},
          textColor={74,84,154},
          horizontalAlignment=TextAlignment.Left),
          stateText=Text(origin={0,0},
          lineColor={74,84,154},
          extent={{-17,-17},{17,9}},
          textString="%algorithm",
          fontSize=16,
          textColor={74,84,154},
          horizontalAlignment=TextAlignment.Left,
          verticalAlignment=TextAlignment.Top),
          stateLine = Line(origin={0,0},
          color = {74, 84, 154},
          points={{-40,22},{40,22}}))}),Protection(access=Access.packageDuplicate));
        algorithm
        annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));  gapS := -5;
        end State1;
        block State2 "状态"
          annotation (__MWORKS(BlockSystem(blockKind=BlockKind.state,SampleTime(auto = true),State),showDiagram = true,sourceModel=SysplorerEmbeddedCoder.StateMachine.State,independentInstance=true,hide=true), defaultComponentName = "state",
           Icon(coordinateSystem(extent={{-100, -100}, {100, 100}},
             grid={2, 2}), graphics={Rectangle(origin = {0, 0},
             lineColor = {74, 84, 154},
             fillColor = {255, 255, 255},
             lineThickness = 1,
             extent = {{-100, 100}, {100, -100}},
             radius = 11), Line(origin = {0, 80},
             points = {{-100, 0}, {100, 0}},
             color = {74, 84, 154}, thickness = 1), Text(origin = {0, 90},
             lineColor = {0, 0, 128},
             extent = {{-100, 10}, {100, -10}},
             textString = "%name",
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128}), Text(origin = {0, -10},
             lineColor = {0, 0, 128},
             extent = {{-100, 90}, {100, -90}},
             textString = "algorithm",
             fontSize = 16,
             textStyle = {TextStyle.None},
             textColor = {0, 0, 128},
             horizontalAlignment = TextAlignment.Left,
             verticalAlignment = TextAlignment.Top)}),
           Diagram(coordinateSystem(extent={{-19.5,-17},{19.5,17}},
          initialScale=1,
          grid={2,2}),graphics = {State(origin={0,0},
          stateTitle=Text(origin={0,0},
          lineColor={74,84,154},
          extent={{-17.5,9},{17.5,17}},
          textString="%name",
          fontSize=16,
          textStyle={TextStyle.Bold},
          textColor={74,84,154},
          horizontalAlignment=TextAlignment.Left),
          stateText=Text(origin={0,0},
          lineColor={74,84,154},
          extent={{-17.5,-17},{17.5,9}},
          textString="%algorithm",
          fontSize=16,
          textColor={74,84,154},
          horizontalAlignment=TextAlignment.Left,
          verticalAlignment=TextAlignment.Top),
          stateLine = Line(origin={0,0},
          color = {74, 84, 154},
          points={{-40,22},{40,22}}))}),Protection(access=Access.packageDuplicate));
        algorithm
        annotation(__MWORKS(BlockSystem(StateMachine(actionKind = ActionKind.entry or ActionKind.during))));  gapS := 5;
        end State2;
      equation
        initialState(state1, true, 1) 
        annotation(Line(origin={162.626,-4.75},
points={{0,10},{0,-10}},
color={113,119,170},
smooth=Smooth.Bezier),Text(origin={0,0},
lineColor={74,84,154},
extent={{0,-3},{0,3}},
textString="%condition",
fontSize=10,
textStyle={TextStyle.Bold},
textColor={74,84,154}), displayText ="[true]",__MWORKS(BlockSystem(StateMachine(outerTransition=false))));
        transition(state1, turn_left, steer < 0, reset = false) 
        annotation(Line(origin={204.5,-16.0111},
points={{-19.5,-7.52426},{19.5,7.52426}},
color={113,119,170},
smooth=Smooth.Bezier),Text(origin={-12.3613,6.44937},
lineColor={74,84,154},
extent={{0,-3},{0,3}},
textString="%condition",
fontSize=10,
textStyle={TextStyle.Bold},
textColor={74,84,154},
horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition=true))), displayText ="[steer < 0]");
        transition(state1, turn_right, steer > 0, reset = false, priority = 2) 
        annotation(Line(origin={204.75,-41.6742},
points={{-19.75,8.4648},{19.75,-8.4648}},
color={113,119,170},
smooth=Smooth.Bezier),Text(origin={-7.52426,6.98682},
lineColor={74,84,154},
extent={{0,-3},{0,3}},
textString="%condition",
fontSize=10,
textStyle={TextStyle.Bold},
textColor={74,84,154},
horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition=true))), displayText ="[steer > 0]");
      end State;
    equation
      initialState(cruise, true, 1) 
      annotation(Line(origin={-84.8041,32.9357},
points={{0,10.4357},{0,-10.4357}},
color={113,119,170},
smooth=Smooth.Bezier),Text(origin={0,0},
lineColor={74,84,154},
extent={{0,-3},{0,3}},
textString="%condition",
fontSize=10,
textStyle={TextStyle.Bold},
textColor={74,84,154}), displayText = "[true]",__MWORKS(BlockSystem(StateMachine(outerTransition=false))));
      transition(cruise, avoid, flag, reset = false) 
      annotation(Line(origin={97,-5.23005},
      points={{-41,-8.88178e-15},{41,8.88178e-15}},
      color={113,119,170},
      smooth=Smooth.Bezier),Text(origin={-3.42187,-4.32236},
      lineColor={74,84,154},
      extent={{0,-3},{0,3}},
      textString="%condition",
      fontSize=10,
      textStyle={TextStyle.Bold},
      textColor={74,84,154},
      horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true))), displayText ="[flag]");
      transition(avoid, cruise, not flag, reset = false) 
      annotation(Line(origin={97,-47.5641},
      points={{41,0},{-41,0}},
      color={113,119,170},
      smooth=Smooth.Bezier),Text(origin={-4.32236,-6.66363},
      lineColor={74,84,154},
      extent={{0,-3},{0,3}},
      textString="%condition",
      fontSize=10,
      textStyle={TextStyle.Bold},
      textColor={74,84,154},
      horizontalAlignment=TextAlignment.Left), __MWORKS(BlockSystem(StateMachine(outerTransition = true))), displayText = "[not flag]");
    end State2;
    equation
    end Chart;
  model ModelWorkspace
    annotation(__MWORKS(hide = true,BlockSystem(blockKind=BlockKind.modelWorkspace)));
  end ModelWorkspace;
equation
  connect(front_dist, abs1.u) 
  annotation(Line(origin={-71,36},
points={{-53,22},{-38.8,22}},
color={0,0,0}));
  connect(saturation.u, sum1.y) 
  annotation(Line(origin={105,-58},
points={{23.2,26.5},{15,26.5},{15,60},{51,60},{51,86},{46.8,86}},
color={0,0,0}),__MWORKS(BlockSystem(NamedSignal)));
  connect(chart.steer, sum1.u1) 
  annotation(Line(origin={45,-37},
points={{-32.2,15.5},{-13,15.5},{-13,70},{83.2,70}},
color={0,0,0}));
  connect(constant1.y, sum2.u2) 
  annotation(Line(origin={9,-98},
points={{3.8,40},{21,40},{21,66.5},{31.2,66.5}},
color={0,0,0}));
  connect(chart.steer, sum2.u1) 
  annotation(Line(origin={16,-49},
points={{-3.2,27.5},{24.2,27.5}},
color={0,0,0}),__MWORKS(BlockSystem(NamedSignal)));
  connect(constant2.y, product1.u2) 
  annotation(Line(origin={41,-81},
points={{22.8,23},{33,23},{33,44.5},{41.2,44.5}},
color={0,0,0}));
  connect(sum2.y, product1.u1) 
  annotation(Line(origin={59,-45},
points={{4.8,18.5},{23.2,18.5}},
color={0,0,0}),__MWORKS(BlockSystem(NamedSignal)));
  connect(product1.y, roundingFunction.u) 
  annotation(Line(origin={77,-8},
points={{28.8,-23.5},{35,-23.5},{35,0},{-35,0},{-35,24},{-26.8,24}},
color={0,0,0}));
  connect(roundingFunction.y, gain.u) 
  annotation(Line(origin={78,16},
  points={{-4.2,0},{4.2,0}},
  color={0,0,0}));
  connect(gain.y, sum1.u2) 
  annotation(Line(origin={117,20},
points={{-11.2,-4},{-4.1,-4},{-4.1,3},{11.2,3}},
color={0,0,0}));
  connect(abs1.y, chart.df) 
  annotation(Line(origin={-49,42},
points={{-37.2,16},{-11,16},{-11,-27.25},{0.2,-27.25}},
color={0,0,0}));
  connect(fl_dist, abs2.u) 
  annotation(Line(origin={-117,16},
  points={{-7,0},{7.2,0}},
  color={0,0,0}));
  connect(left_dist, abs3.u) 
  annotation(Line(origin={-117,-64.3},
points={{-7,0},{7.2,0}},
color={0,0,0}));
  connect(abs3.y, chart.dl) 
  annotation(Line(origin={-67,-20},
points={{-19.2,-44.3},{-1,-44.3},{-1,1.4},{18.2,1.4}},
color={0,0,0}));
  connect(right_dist, abs4.u) 
  annotation(Line(origin={-117,-18.6},
points={{-7,0},{7.2,0}},
color={0,0,0}));
  connect(abs4.y, chart.dr) 
  annotation(Line(origin={-67,-48},
points={{-19.2,29.4},{-5,29.4},{-5,41},{18.2,41}},
color={0,0,0}));
  connect(saturation.y, steer) 
  annotation(Line(origin={179,-32},
points={{-27.2,0.5},{-23,0.5},{-23,-26},{-13,-26}},
color={0,0,0}));
  connect(fr_dist, abs5.u) 
  annotation(Line(origin={-117,-110},
  points={{-7,0},{7.2,0}},
  color={0,0,0}));
  connect(abs5.y, chart.dfr) 
  annotation(Line(origin={-67,-70},
  points={{-19.2,-40},{9,-40},{9,39.8},{18.2,39.8}},
  color={0,0,0}));
  connect(abs2.y, chart.dfl) 
  annotation(Line(origin={-67,10},
  points={{-19.2,6},{-5,6},{-5,-5.4},{18.2,-5.4}},
  color={0,0,0}));
  connect(chart.gapS, gap) 
  annotation(Line(origin={89,-68},
points={{-76.2,41.6667},{-67,41.6667},{-67,-42},{77,-42}},
color={0,0,0}));
  connect(chart.speed, gain1.u) 
  annotation(Line(origin={52,35},
  points={{-39.2,-22.6667},{-26,-22.6667},{-26,23},{38.2,23}},
  color={0,0,0}));
  connect(gain1.y, speed) 
  annotation(Line(origin={140,58},
  points={{-26.2,0},{26,0}},
  color={0,0,0}));
  end ObsAvoidController_Sysblock7g1;